language: php

php:
  - 7.2
  - 7.1
  - 7.0

env:
  - LARAVEL_VERSION=6.2.*
  - LARAVEL_VERSION=6.1.*
  - LARAVEL_VERSION=5.9.*
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=5.7.*
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.5.*

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: LARAVEL_VERSION=5.6.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction         - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - phpunit
