name: Snyk PHP Vulnerability Checker
on:
  push:
    branches: [ master, 2.x ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 12 * * 5'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/php@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        working-directory: /
        file: composer.json
